In [1]:
import numpy as np 
import pandas as pd 
from datetime import datetime

In [8]:
#Almost done. Only thing to do now is to ensure that the datecounts columns is returned in chronological order.

def convert(string):
    """Converts from string to datetime
    """
    date = datetime.strptime(string,'%m/%d/%Y') #Accepts date string, converts it to datetime object. 
    return date



def hwarrests(csv):
    """
    Returns dataframe which displays the total number of arrests in Hollywood per 
    day, every day since January 1st, 2017. CURRENTLY NOT THERE YET
    """
    
    df = pd.read_csv(csv) #Reads csv file and forms a new dataframe 
    
    hdf = df[df['Area ID'] == 6] #Filters dataframe to only include date from Hollywood. 
    hdf['Converted Dates'] = hdf['Arrest Date'].apply(convert, 0) #Applies convert function to all dates in 'Arrest Date Column', and places those dates in new column called 'Converted Dates'
    
    
    
    start_date = datetime.strptime('1/1/2017','%m/%d/%Y') #Sets start date for filter
    end_date = datetime.strptime('12/31/2019','%m/%d/%Y') # Sets end date for filter 
    
    hdf = hdf[(hdf['Converted Dates'] >= start_date) & (hdf['Converted Dates'] <= end_date)] #Filters hdf to only include dates between start and end dates. 

    
    datecounts = pd.DataFrame(columns = ['Date', 'Number of Arrests']) #Creates empty dataframe with dates and number of arrests as columns
    dateray = np.array(hdf['Arrest Date'])  #Creates array of arrest dates in hdf
    unique_elements, counts_elements = np.unique(dateray, return_counts=True) #Returns two arrays with (1) unique dates and (2) number of arrests for those dates
    datecounts['Date'] = unique_elements #Sets array for unique dates to 'Date' in datecounts
    datecounts['Number of Arrests'] = counts_elements #sets array for arrest counts per date to 'Number of Arrest' in datecounts
    return datecounts #Returns datecounts dataframe
    
    

hwarrests('arrestdata.csv') #Calls hwarrests functions on LA arrest dataset.

/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

            Date  Number of Arrests
0     01/01/2017                 20
1     01/01/2018                 28
2     01/01/2019                 20
3     01/02/2017                  4
4     01/02/2018                 17
5     01/02/2019                 16
6     01/03/2017                 19
7     01/03/2018                 39
8     01/03/2019                 11
9     01/04/2017                 35
10    01/04/2018                 37
11    01/04/2019                 17
12    01/05/2017                 41
13    01/05/2018                 34
14    01/05/2019                 30
15    01/06/2017                 21
16    01/06/2018                 16
17    01/06/2019                 11
18    01/07/2017                  9
19    01/07/2018                 18
20    01/07/2019                  9
21    01/08/2017                 14
22    01/08/2018                 12
23    01/08/2019                 19
24    01/09/2017                  8
25    01/09/2018                 11
26    01/09/2019                 15
27    01/10/2017                  9
28    01/10/2018                 17
29    01/10/2019                 49
...          ...                ...
1065  12/22/2017                 22
1066  12/22/2018                  8
1067  12/22/2019                  9
1068  12/23/2017                 18
1069  12/23/2018                 11
1070  12/23/2019                  7
1071  12/24/2017                  8
1072  12/24/2018                  5
1073  12/24/2019                  9
1074  12/25/2017                  4
1075  12/25/2018                 10
1076  12/25/2019                  7
1077  12/26/2017                  6
1078  12/26/2018                  8
1079  12/26/2019                 13
1080  12/27/2017                 22
1081  12/27/2018                 21
1082  12/27/2019                 13
1083  12/28/2017                 51
1084  12/28/2018                 11
1085  12/28/2019                  8
1086  12/29/2017                 31
1087  12/29/2018                  8
1088  12/29/2019                 28
1089  12/30/2017                 18
1090  12/30/2018                  9
1091  12/30/2019                 14
1092  12/31/2017                 26
1093  12/31/2018                  8
1094  12/31/2019                 11

[1095 rows x 2 columns]