In [13]:
import numpy as np 
import pandas as pd 
from datetime import datetime

In [14]:
def convert(string):
    """Converts from string to datetime
    """
    date = datetime.strptime(string,'%m/%d/%Y') #Accepts date string, converts it to datetime object. 
    return date


def hwarrests(csv):
    """
    Returns dataframe which displays the total number of arrests in Hollywood per 
    day, every day since January 1st, 2017.  
    """
    
    df = pd.read_csv(csv) #Reads csv file and forms a new dataframe 
    
    hdf = df[df['Area ID'] == 6] #Filters dataframe to only include date from Hollywood. 
    hdf['Converted Dates'] = hdf['Arrest Date'].apply(convert, 0) #Applies convert function to all dates in 'Arrest Date Column', and places those dates in new column called 'Converted Dates'
    
    
    start_date = datetime.strptime('1/1/2017','%m/%d/%Y') #Sets start date for filter
    end_date = datetime.strptime('12/31/2019','%m/%d/%Y') # Sets end date for filter      
    hdf = hdf[(hdf['Converted Dates'] >= start_date) & (hdf['Converted Dates'] <= end_date)] #Filters hdf to only include dates between start and end dates. 

    
    datecounts = pd.DataFrame(columns = ['Date', 'Number of Arrests']) #Creates empty dataframe with dates and number of arrests as columns
    dateray = np.array(hdf['Converted Dates'])  #Creates array of arrest dates in hdf
    unique_elements, counts_elements = np.unique(dateray, return_counts = True) #Returns two arrays with (1) unique dates and (2) number of arrests for those dates
    datecounts['Date'] = unique_elements #Sets array for unique dates to 'Date' in datecounts
    datecounts['Number of Arrests'] = counts_elements #sets array for arrest counts per date to 'Number of Arrest' in datecounts
    
    #Checks for dates which are not present in the dataframe and assigns corresponding count to 0. 
    idx = pd.date_range(start_date, end_date) 
    s = pd.Series(datecounts['Number of Arrests'])
    s.index = datecounts['Date']
    s = s.reindex(idx, fill_value = 0) 
    datecounts = pd.DataFrame({'Date':s.index, 'Number of Arrests':s.values})
    
    return datecounts.sort_values(by = 'Date') #Returns datecounts dataframe sorted by chronological order
    
    

hwarrests('arrestdata.csv') #Calls hwarrests functions on LA arrest dataset.

/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

           Date  Number of Arrests
0    2017-01-01                 20
1    2017-01-02                  4
2    2017-01-03                 19
3    2017-01-04                 35
4    2017-01-05                 41
5    2017-01-06                 21
6    2017-01-07                  9
7    2017-01-08                 14
8    2017-01-09                  8
9    2017-01-10                  9
10   2017-01-11                 19
11   2017-01-12                 39
12   2017-01-13                 41
13   2017-01-14                  7
14   2017-01-15                 11
15   2017-01-16                  5
16   2017-01-17                 19
17   2017-01-18                 19
18   2017-01-19                 15
19   2017-01-20                 25
20   2017-01-21                 23
21   2017-01-22                 19
22   2017-01-23                  4
23   2017-01-24                 12
24   2017-01-25                 10
25   2017-01-26                 25
26   2017-01-27                 23
27   2017-01-28                 29
28   2017-01-29                 20
29   2017-01-30                  7
...         ...                ...
1065 2019-12-02                 11
1066 2019-12-03                  8
1067 2019-12-04                 12
1068 2019-12-05                 11
1069 2019-12-06                  9
1070 2019-12-07                 11
1071 2019-12-08                  7
1072 2019-12-09                 10
1073 2019-12-10                 21
1074 2019-12-11                 10
1075 2019-12-12                 13
1076 2019-12-13                 23
1077 2019-12-14                 47
1078 2019-12-15                  9
1079 2019-12-16                  9
1080 2019-12-17                 10
1081 2019-12-18                  8
1082 2019-12-19                 18
1083 2019-12-20                 11
1084 2019-12-21                 10
1085 2019-12-22                  9
1086 2019-12-23                  7
1087 2019-12-24                  9
1088 2019-12-25                  7
1089 2019-12-26                 13
1090 2019-12-27                 13
1091 2019-12-28                  8
1092 2019-12-29                 28
1093 2019-12-30                 14
1094 2019-12-31                 11

[1095 rows x 2 columns]

In [15]:
def convert(string):
    """Converts from string to datetime
    """
    date = datetime.strptime(string,'%m/%d/%Y') #Accepts date string, converts it to datetime object. 
    return date


def hwvehstops(csv):
    """ 
    Reads csv file and returns dataframe which displays total number of
    vehicle stops in Hollywood for every day between January 1st, 2017 and December 31, 2019.
    Code currently only reads data from 2017. 
    """
    
    df = pd.read_csv(csv)
    hdf = df[(df['Division Description 1'] == 'HOLLYWOOD') & (df['Stop Type'] == 'VEH')] #Filters dataframe to only include Hollywood pedestrian stops. 
    hdf['Converted Dates'] = hdf['Stop Date'].apply(convert, 0)
    
    
    
    start_date = datetime.strptime('1/1/2017','%m/%d/%Y') #Sets start date for filter
    end_date = datetime.strptime('12/31/2019','%m/%d/%Y') # Sets end date for filter
    
    
    
    hdf = hdf[(hdf['Converted Dates'] >= start_date) & (hdf['Converted Dates'] <= end_date)] #Filters hdf to only include relevant dates
    
    
    datecounts = pd.DataFrame(columns = ['Date', 'Number of Vehicle Stops'])
    dateray = np.array(hdf['Converted Dates'])
    unique_elements, counts_elements = np.unique(dateray, return_counts = True)
    
    datecounts['Date'] = unique_elements
    datecounts['Number of Vehicle Stops'] = counts_elements
    
    
    #Checks for dates which are not present in the dataframe and assigns corresponding count to 0. 
    idx = pd.date_range(start_date, end_date) 
    s = pd.Series(datecounts['Number of Vehicle Stops'])
    s.index = datecounts['Date']
    s = s.reindex(idx, fill_value=0) 
    datecounts = pd.DataFrame({'Date':s.index, 'Number of Vehicle Stops':s.values})
    
    return datecounts



def hwpedstops(csv):
    """ 
    Reads csv file and returns dataframe which displays total number of
    pedestrian stops in Hollywood for every day between January 1st, 2017 and December 31, 2019.
    Code currently only reads data from 2017. 
    """
    
    df = pd.read_csv(csv)
    hdf = df[(df['Division Description 1'] == 'HOLLYWOOD') & (df['Stop Type'] == 'PED')] #Filters dataframe to only include Hollywood pedestrian stops. 
    hdf['Converted Dates'] = hdf['Stop Date'].apply(convert, 0)
    
    
    
    start_date = datetime.strptime('1/1/2017','%m/%d/%Y') #Sets start date for filter
    end_date = datetime.strptime('12/31/2019','%m/%d/%Y') # Sets end date for filter
    
    
    
    hdf = hdf[(hdf['Converted Dates'] >= start_date) & (hdf['Converted Dates'] <= end_date)] #Filters hdf to only include relevant dates
    
    
    datecounts = pd.DataFrame(columns = ['Date', 'Number of Pedestrian Stops'])
    dateray = np.array(hdf['Converted Dates'])
    unique_elements, counts_elements = np.unique(dateray, return_counts = True)
    
    datecounts['Date'] = unique_elements
    datecounts['Number of Pedestrian Stops'] = counts_elements
    
    #Checks for dates which are not present in the dataframe and assigns corresponding count to 0. 
    idx = pd.date_range(start_date, end_date) 
    s = pd.Series(datecounts['Number of Pedestrian Stops'])
    s.index = datecounts['Date']
    s = s.reindex(idx, fill_value=0) 
    datecounts = pd.DataFrame({'Date':s.index, 'Number of Pedestrian Stops':s.values})
    
    return datecounts
    
def combined(csv):
    """
    Returns combined dataframe for vehicle and pedestrian counts.
    """
    vehdf = hwvehstops('vehped.csv')
    peddf = hwpedstops('vehped.csv')
        
    peddf['Number of Vehicle Stops'] = vehdf['Number of Vehicle Stops'] #Creates new column in peddf with vehicle stop counts.
    
    return peddf #Returns combined dataframe


combined('vehped.csv')

/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3325: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

           Date  Number of Pedestrian Stops  Number of Vehicle Stops
0    2017-01-01                          12                       33
1    2017-01-02                           4                       24
2    2017-01-03                          16                       33
3    2017-01-04                          31                       26
4    2017-01-05                          24                       33
5    2017-01-06                          34                       46
6    2017-01-07                          18                       69
7    2017-01-08                          22                       38
8    2017-01-09                          10                       27
9    2017-01-10                          11                       24
10   2017-01-11                          10                       40
11   2017-01-12                          35                       31
12   2017-01-13                          40                       47
13   2017-01-14                          13                       57
14   2017-01-15                          14                       66
15   2017-01-16                           9                       21
16   2017-01-17                           9                       27
17   2017-01-18                          12                       10
18   2017-01-19                          17                       25
19   2017-01-20                          19                       59
20   2017-01-21                          35                      115
21   2017-01-22                          26                       52
22   2017-01-23                           3                       23
23   2017-01-24                          12                       23
24   2017-01-25                           5                       34
25   2017-01-26                          25                       35
26   2017-01-27                          23                       32
27   2017-01-28                          46                       53
28   2017-01-29                          20                       26
29   2017-01-30                           1                       10
...         ...                         ...                      ...
1065 2019-12-02                          31                       17
1066 2019-12-03                          20                       21
1067 2019-12-04                          12                       17
1068 2019-12-05                          16                       35
1069 2019-12-06                          26                       30
1070 2019-12-07                          24                       29
1071 2019-12-08                          11                       28
1072 2019-12-09                          30                       38
1073 2019-12-10                          29                       12
1074 2019-12-11                          19                       34
1075 2019-12-12                          25                       33
1076 2019-12-13                          36                       58
1077 2019-12-14                          52                       63
1078 2019-12-15                          53                       35
1079 2019-12-16                          17                       24
1080 2019-12-17                          16                       50
1081 2019-12-18                          23                       29
1082 2019-12-19                          23                       29
1083 2019-12-20                          17                       22
1084 2019-12-21                          22                       21
1085 2019-12-22                          20                       26
1086 2019-12-23                          24                       14
1087 2019-12-24                          11                       18
1088 2019-12-25                          12                        6
1089 2019-12-26                          22                       34
1090 2019-12-27                          14                       65
1091 2019-12-28                          29                       37
1092 2019-12-29                          44                       64
1093 2019-12-30                          49                       32
1094 2019-12-31                          13                       33

[1095 rows x 3 columns]

In [16]:
def convert(string):
    """Converts from string to datetime
    """
    date = datetime.strptime(string[:10],'%m/%d/%Y') #Accepts date string, converts it to datetime object. 
    return date


def hwcrimes(csv):
    """ 
    Reads csv file and returns dataframe which displays total number of
    crimes committed in Hollywood for every day between January 1st, 2017 and December 31, 2019. 
    Data: https://data.lacity.org/A-Safe-City/Crime-Data-from-2010-to-2019/63jg-8b9z/data
    """
    
    df = pd.read_csv(csv)
    hdf = df[df['AREA '] == 6] #Filters dataframe to only include Hollywood pedestrian stops. 
    hdf['Converted Dates'] = hdf['DATE OCC'].apply(convert, 0)
    
    
    
    start_date = datetime.strptime('1/1/2017','%m/%d/%Y') #Sets start date for filter
    end_date = datetime.strptime('12/31/2019','%m/%d/%Y') # Sets end date for filter
    
    
    
    hdf = hdf[(hdf['Converted Dates'] >= start_date) & (hdf['Converted Dates'] <= end_date)] #Filters hdf to only include relevant dates
    
    
    datecounts = pd.DataFrame(columns = ['Date', 'Number of Crimes Committed'])
    dateray = np.array(hdf['Converted Dates'])
    unique_elements, counts_elements = np.unique(dateray, return_counts = True)
    
    datecounts['Date'] = unique_elements
    datecounts['Number of Crimes Committed'] = counts_elements
    
    #Checks for dates which are not present in the dataframe and assigns corresponding count to 0. 
    idx = pd.date_range(start_date, end_date) 
    s = pd.Series(datecounts['Number of Crimes Committed'])
    s.index = datecounts['Date']
    s = s.reindex(idx, fill_value=0) 
    datecounts = pd.DataFrame({'Date':s.index, 'Number of Crimes Committed':s.values})
    
    return datecounts
    

hwcrimes('hwcrime.csv')

/Users/varunbopardikar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

           Date  Number of Crimes Committed
0    2017-01-01                          66
1    2017-01-02                          28
2    2017-01-03                          32
3    2017-01-04                          19
4    2017-01-05                          25
5    2017-01-06                          22
6    2017-01-07                          23
7    2017-01-08                          28
8    2017-01-09                          13
9    2017-01-10                          28
10   2017-01-11                          25
11   2017-01-12                          41
12   2017-01-13                          28
13   2017-01-14                          31
14   2017-01-15                          34
15   2017-01-16                          23
16   2017-01-17                          34
17   2017-01-18                          20
18   2017-01-19                          22
19   2017-01-20                          28
20   2017-01-21                          32
21   2017-01-22                          33
22   2017-01-23                          24
23   2017-01-24                          26
24   2017-01-25                          32
25   2017-01-26                          32
26   2017-01-27                          24
27   2017-01-28                          30
28   2017-01-29                          38
29   2017-01-30                          24
...         ...                         ...
1065 2019-12-02                          21
1066 2019-12-03                          22
1067 2019-12-04                          30
1068 2019-12-05                          26
1069 2019-12-06                          23
1070 2019-12-07                          36
1071 2019-12-08                          31
1072 2019-12-09                          20
1073 2019-12-10                          35
1074 2019-12-11                          28
1075 2019-12-12                          20
1076 2019-12-13                          31
1077 2019-12-14                          37
1078 2019-12-15                          40
1079 2019-12-16                          35
1080 2019-12-17                          29
1081 2019-12-18                          26
1082 2019-12-19                          28
1083 2019-12-20                          22
1084 2019-12-21                          39
1085 2019-12-22                          37
1086 2019-12-23                          20
1087 2019-12-24                          18
1088 2019-12-25                          22
1089 2019-12-26                          20
1090 2019-12-27                          28
1091 2019-12-28                          26
1092 2019-12-29                          27
1093 2019-12-30                          34
1094 2019-12-31                          33

[1095 rows x 2 columns]